"use client";

import { useSyncExternalStore } from "react";

// Google Cast Web Sender prototype. Push short spoken announcements to a
// Google Home / Chromecast Audio / Cast-compatible speaker via the Default
// Media Receiver — no receiver app to publish.
//
// Docs: https://developers.google.com/cast/docs/web_sender/integrate
//
// Namespacing gotcha: framework APIs (CastContext, SessionState, event
// enums) live under cast.framework.*; everything else (AutoJoinPolicy,
// MediaInfo, LoadRequest, MetadataType, GenericMediaMetadata) lives under
// chrome.cast.*. Getting this wrong surfaces as "Cast framework unavailable".
//
// Prototype caveats:
// - Audio is generated by /api/tts (Google Translate TTS proxy), undocumented
//   and may break at any time. Fine for kitchen use; swap for a real TTS
//   provider before shipping.
// - Requires HTTPS (Chrome blocks the sender SDK off localhost otherwise).
// - The Home must be on the same network as the browser.

type CastStatus =
  | "unsupported"
  | "unavailable"
  | "disconnected"
  | "connecting"
  | "connected";

export type CastState = {
  status: CastStatus;
  deviceName: string | null;
  error: string | null;
};

const INITIAL: CastState = {
  status: typeof window === "undefined" ? "unsupported" : "unavailable",
  deviceName: null,
  error: null,
};

let state: CastState = INITIAL;
const listeners = new Set<() => void>();
function setState(next: Partial<CastState>) {
  state = { ...state, ...next };
  listeners.forEach((cb) => cb());
}
function subscribe(cb: () => void) {
  listeners.add(cb);
  return () => {
    listeners.delete(cb);
  };
}

export function useCastState(): CastState {
  return useSyncExternalStore(subscribe, () => state, () => INITIAL);
}

// ── SDK loader ─────────────────────────────────────────────────────────────

declare global {
  interface Window {
    __onGCastApiAvailable?: (isAvailable: boolean) => void;
  }
}

const SDK_URL =
  "https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1";
const DEFAULT_MEDIA_RECEIVER = "CC1AD845";

let sdkPromise: Promise<void> | null = null;

function loadSdk(): Promise<void> {
  if (typeof window === "undefined") return Promise.reject(new Error("no window"));
  if (sdkPromise) return sdkPromise;
  sdkPromise = new Promise<void>((resolve, reject) => {
    window.__onGCastApiAvailable = (isAvailable: boolean) => {
      if (isAvailable) resolve();
      else reject(new Error("Cast API not available"));
    };
    const script = document.createElement("script");
    script.src = SDK_URL;
    script.async = true;
    script.onerror = () => reject(new Error("Failed to load Cast SDK"));
    document.head.appendChild(script);
  });
  return sdkPromise;
}

// Loose any-typed accessors so we don't depend on @types/chromecast-caf-sender.
type LooseFramework = {
  CastContext: { getInstance: () => LooseContext };
  SessionState: {
    SESSION_STARTED: string;
    SESSION_RESUMED: string;
    SESSION_ENDED: string;
  };
  CastContextEventType: { SESSION_STATE_CHANGED: string };
};
type LooseChromeCast = {
  AutoJoinPolicy: { ORIGIN_SCOPED: string };
  media: {
    MediaInfo: new (url: string, type: string) => LooseMediaInfo;
    LoadRequest: new (info: LooseMediaInfo) => unknown;
    MetadataType: { GENERIC: number };
    GenericMediaMetadata: new () => LooseMetadata;
    DEFAULT_MEDIA_RECEIVER_APP_ID?: string;
  };
};
type LooseContext = {
  setOptions: (o: { receiverApplicationId: string; autoJoinPolicy: string }) => void;
  getCurrentSession: () => LooseSession | null;
  requestSession: () => Promise<string | void>;
  addEventListener: (event: string, cb: (e: { sessionState: string }) => void) => void;
};
type LooseSession = {
  getCastDevice: () => { friendlyName: string };
  loadMedia: (req: unknown) => Promise<void>;
  endSession: (stopCasting: boolean) => void;
};
type LooseMediaInfo = {
  contentType: string;
  metadata?: LooseMetadata;
};
type LooseMetadata = {
  metadataType: number;
  title?: string;
};

function getFramework(): LooseFramework | null {
  const w = window as unknown as { cast?: { framework?: LooseFramework } };
  return w.cast?.framework ?? null;
}
function getChromeCast(): LooseChromeCast | null {
  const w = window as unknown as { chrome?: { cast?: LooseChromeCast } };
  return w.chrome?.cast ?? null;
}
function getContext(): LooseContext | null {
  return getFramework()?.CastContext.getInstance() ?? null;
}

export async function initCast(): Promise<void> {
  if (typeof window === "undefined") return;
  const hasChrome = "chrome" in window;
  if (!hasChrome) {
    setState({ status: "unsupported", error: "Cast requires a Chromium browser" });
    return;
  }
  try {
    await loadSdk();
    const framework = getFramework();
    const chromeCast = getChromeCast();
    const ctx = getContext();
    if (!framework || !chromeCast || !ctx) {
      setState({
        status: "unsupported",
        error: "Cast framework unavailable (check for ad-blockers on gstatic.com)",
      });
      return;
    }
    ctx.setOptions({
      receiverApplicationId:
        chromeCast.media.DEFAULT_MEDIA_RECEIVER_APP_ID ?? DEFAULT_MEDIA_RECEIVER,
      autoJoinPolicy: chromeCast.AutoJoinPolicy.ORIGIN_SCOPED,
    });
    ctx.addEventListener(
      framework.CastContextEventType.SESSION_STATE_CHANGED,
      (e) => {
        const S = framework.SessionState;
        if (
          e.sessionState === S.SESSION_STARTED ||
          e.sessionState === S.SESSION_RESUMED
        ) {
          const session = ctx.getCurrentSession();
          setState({
            status: "connected",
            deviceName: session?.getCastDevice().friendlyName ?? null,
            error: null,
          });
        } else if (e.sessionState === S.SESSION_ENDED) {
          setState({ status: "disconnected", deviceName: null });
        }
      }
    );
    const existing = ctx.getCurrentSession();
    if (existing) {
      setState({
        status: "connected",
        deviceName: existing.getCastDevice().friendlyName,
        error: null,
      });
    } else {
      setState({ status: "disconnected", error: null });
    }
  } catch (err) {
    setState({
      status: "unsupported",
      error: err instanceof Error ? err.message : String(err),
    });
  }
}

export async function connectCast(): Promise<void> {
  if (state.status === "unsupported") return;
  let ctx = getContext();
  if (!ctx) {
    await initCast();
    ctx = getContext();
    if (!ctx) return;
  }
  setState({ status: "connecting", error: null });
  try {
    await ctx.requestSession();
  } catch (err) {
    setState({
      status: "disconnected",
      error: err instanceof Error ? err.message : String(err),
    });
  }
}

export function disconnectCast() {
  const ctx = getContext();
  const session = ctx?.getCurrentSession();
  if (session) session.endSession(true);
  setState({ status: "disconnected", deviceName: null });
}

export async function speakOnCast(text: string): Promise<void> {
  const ctx = getContext();
  const session = ctx?.getCurrentSession();
  const chromeCast = getChromeCast();
  if (!session || !chromeCast?.media) return;
  const origin = typeof window !== "undefined" ? window.location.origin : "";
  const url = `${origin}/api/tts?q=${encodeURIComponent(text)}`;
  const mediaInfo = new chromeCast.media.MediaInfo(url, "audio/mpeg");
  const metadata = new chromeCast.media.GenericMediaMetadata();
  metadata.metadataType = chromeCast.media.MetadataType.GENERIC;
  metadata.title = text;
  mediaInfo.metadata = metadata;
  const req = new chromeCast.media.LoadRequest(mediaInfo);
  try {
    await session.loadMedia(req);
  } catch (err) {
    console.warn("[cast] loadMedia failed", err);
  }
}
