export type Ingredient = {
  quantity: string | null;
  unit: string | null;
  item: string;
  prep: string | null;
  note: string | null;
};

export type StepIcon =
  | "flame"      // sear, brown, sauté, fry
  | "soup"       // simmer, sauce, stew
  | "boil"       // boil, blanch
  | "oven"       // bake, roast, broil
  | "knife"      // chop, slice, dice, prep
  | "wine"       // deglaze, add liquid/wine
  | "leaf"       // herbs, garnish, fresh add
  | "mix"        // combine, stir, fold, whisk
  | "salt"       // season, finish with salt
  | "rest"       // chill, rest, marinate, wait
  | "serve"      // plate, serve
  | "blend";     // blend, purée, emulsify

export type Step = {
  number: number;
  headline: string;
  action: string;
  icon: StepIcon;
  ingredients: Ingredient[];
  equipment: string[];
  temperature: string | null;
  duration: string | null;
  doneness_cue: string | null;
};

// Where a CookCard came from. 'url' = parsed from a real recipe page (the
// original flow). 'instagram-reconstructed' = best-guess reconstruction from
// an Instagram caption + photo when no recipe link was available; timings
// and steps are soft. Missing field on older cached entries means 'url'.
export type Provenance = "url" | "instagram-reconstructed";

export type CookCard = {
  title: string;
  source_url: string;
  // Optional — older cached recipes predate this field. Generated by the
  // parser as one evocative sentence; surfaced in the library rolodex swatch
  // tile and under the title on photo/vignette tiles.
  tagline?: string | null;
  // AI-generated dish photo URL (Vercel Blob). Backfilled by
  // scripts/generate-dish-photos.ts using the local image-gen server. Renders
  // as a fourth MealFace kind ("generated") between real photos and the
  // sprite vignette, with a subtle ✨ badge so users know it's a mockup.
  generated_dish_image_url?: string | null;
  provenance?: Provenance;
  servings: string | null;
  total_time: string | null;
  active_time: string | null;
  equipment: string[];
  pantry_ingredients: Ingredient[];
  steps: Step[];
};
